import matplotlib.pyplot as plt
import networkx as nx
import numpy as np

G = nx.Graph()
G.add_edge('Abu Zubeida', 'Djamal Beghal')
G.add_edge('Jean-Maro Grandvisir', 'Djamal Beghal')
G.add_edge('Nizar Trabelsi', 'Djamal Beghal')
G.add_edge('Abu Walid','Djamal Beghal')
G.add_edge('Abu Walid','Kamel Daoudi')
G.add_edge('Abu Walid','Abu Qatada')
G.add_edge('Djamal Beghal','Kamel Daoudi')
G.add_edge('Djamal Beghal','Jerome Courtaillier')
G.add_edge('Djamal Beghal','Zacarias Moussaoui')
G.add_edge('Djamal Beghal','Abu Qatada')
G.add_edge('Kamel Daoudi','Jerome Courtaillier')
G.add_edge('Kamel Daoudi','Zacarias Moussaoui')
G.add_edge('Jerome Courtaillier','David Courtaillier')
G.add_edge('Jerome Courtaillier','Zacarias Moussaoui')
G.add_edge('David Courtaillier','Zacarias Moussaoui')
G.add_edge('Zacarias Moussaoui','Abu Qatada')
G.add_edge('Zacarias Moussaoui','Ahmed Ressam')
G.add_edge('Zacarias Moussaoui','Ramzi Bin Al-Shibh')
G.add_edge('Zacarias Moussaoui','Mohamed Atta')
G.add_edge('Abu Qatada','Tarek Maaroufi')
G.add_edge('Abu Qatada','Imad E. B. Yarkas')
G.add_edge('Ahmed Ressam','Haydar Abu Doha')
G.add_edge('Haydar Abu Doha','Mehdi Khammoun')
G.add_edge('Haydar Abu Doha','Essid S. B. Khemais')
G.add_edge('Mehdi Khammoun','Essid S. B. Khemais')
G.add_edge('Mehdi Khammoun','Mohamed Bensakhria')
G.add_edge('Mohamed Bensakhria','Tarek Maaroufi')
G.add_edge('Mohamed Bensakhria','Essid S. B. Khemais')
G.add_edge('Mohamed Bensakhria','Lased Ben Heni')
G.add_edge('Tarek Maaroufi','Essoussi Laaroussi')
G.add_edge('Tarek Maaroufi','Essid S. B. Khemais')
G.add_edge('Tarek Maaroufi','Seifallah ben Hassine')
G.add_edge('Tarek Maaroufi','Imad E. B. Yarkas')
G.add_edge('Essoussi Laaroussi','Essid S. B. Khemais')
G.add_edge('Essid S. B. Khemais','Seifallah ben Hassine')
G.add_edge('Essid S. B. Khemais','Lased Ben Heni')
G.add_edge('Essid S. B. Khemais','Fahid al Shakri')
G.add_edge('Essid S. B. Khemais','Madjid Sahoune')
G.add_edge('Essid S. B. Khemais','Samir Kishk')
G.add_edge('Essid S. B. Khemais','Mohamed Atta')
G.add_edge('Imad E. B. Yarkas','Mohamed Atta')
G.add_edge('Imad E. B. Yarkas','Ramzi Bin Al-Shibh')
G.add_edge('Mohammed Belfas','Ramzi Bin Al-Shibh')
G.add_edge('Mohammed Belfas','Agus Budiman')
G.add_edge('Ramzi Bin Al-Shibh','Agus Budiman')
G.add_edge('Ramzi Bin Al-Shibh','Mounir El Motassadeq')
G.add_edge('Ramzi Bin Al-Shibh','Zakariya Essabar')
G.add_edge('Ramzi Bin Al-Shibh','Said Bahaji')
G.add_edge('Ramzi Bin Al-Shibh','Ziad Jarrah')
#G.add_edge('Ramzi Bin Al-Shibh','Marwan Al-Shehhi')
G.add_edge('Ramzi Bin Al-Shibh','Mohamed Atta')
G.add_edge('Abdelghani Mzoudi','Mohamed Atta')
#G.add_edge('Agus Budiman','Marwan Al-Shehhi')
G.add_edge('Agus Budiman','Mohamed Atta')
G.add_edge('Mounir El Motassadeq','Said Bahaji')
G.add_edge('Mounir El Motassadeq','Ziad Jarrah')
#G.add_edge('Mounir El Motassadeq','Marwan Al-Shehhi')
G.add_edge('Mounir El Motassadeq','Mohamed Atta')
G.add_edge('Zakariya Essabar','Said Bahaji')
G.add_edge('Zakariya Essabar','Ziad Jarrah')
#G.add_edge('Zakariya Essabar','Marwan Al-Shehhi')
G.add_edge('Zakariya Essabar','Mohamed Atta')
G.add_edge('Ahmed K. S. Al-Ani','Mohamed Atta')
#G.add_edge('Mustafa Ahmed al-Hisawi','Marwan Al-Shehhi')
G.add_edge('Mustafa Ahmed al-Hisawi','Fayez Ahmed')
G.add_edge('Mustafa Ahmed al-Hisawi','Mohamed Atta')
G.add_edge('Mustafa Ahmed al-Hisawi','Waleed Alshehri')
G.add_edge('Mahmud M. Salim','Mamoun Darkazanli')
G.add_edge('Mamoun Darkazanli','Said Bahaji')
#G.add_edge('Mamoun Darkazanli','Marwan Al-Shehhi')
G.add_edge('Mamoun Darkazanli','Mohamed Atta')
G.add_edge('Said Bahaji','Ziad Jarrah')
#G.add_edge('Said Bahaji','Marwan Al-Shehhi')
G.add_edge('Said Bahaji','Mohamed Atta')
#G.add_edge('Ziad Jarrah','Marwan Al-Shehhi')
G.add_edge('Ziad Jarrah','Mohamed Atta')
G.add_edge('Ziad Jarrah','Ahmed Al Haznawi')
G.add_edge('Ziad Jarrah','Lofti Raissi')
G.add_edge('Ziad Jarrah','Hani Hanjour')
G.add_edge('Ziad Jarrah','Salem Alhazmi*')
#G.add_edge('Marwan Al-Shehhi','Fayez Ahmed')
#G.add_edge('Marwan Al-Shehhi','Mohamed Atta')
#G.add_edge('Marwan Al-Shehhi','Wail Alshehri')
#G.add_edge('Marwan Al-Shehhi','Abdul Aziz Al-Omari*')
#G.add_edge('Marwan Al-Shehhi','Waleed Alshehri')
#G.add_edge('Marwan Al-Shehhi','Satam Suqami')
#G.add_edge('Marwan Al-Shehhi','Hamza Alghamdi')
#G.add_edge('Marwan Al-Shehhi','Lofti Raissi')
#G.add_edge('Marwan Al-Shehhi','Hani Hanjour')
#G.add_edge('Marwan Al-Shehhi','Salem Alhazmi*')
G.add_edge('Fayez Ahmed','Mohamed Atta')
G.add_edge('Fayez Ahmed','Wail Alshehri')
G.add_edge('Fayez Ahmed','Abdul Aziz Al-Omari*')
G.add_edge('Fayez Ahmed','Waleed Alshehri')
G.add_edge('Fayez Ahmed','Satam Suqami')
G.add_edge('Fayez Ahmed','Mohand Alshehri*')
G.add_edge('Mohamed Atta','Wail Alshehri')
G.add_edge('Mohamed Atta','Abdul Aziz Al-Omari*')
G.add_edge('Mohamed Atta','Satam Suqami')
G.add_edge('Mohamed Atta','Ahmed Al Haznawi')
G.add_edge('Mohamed Atta','Lofti Raissi')
G.add_edge('Mohamed Atta','Hani Hanjour')
G.add_edge('Mohamed Atta','Nawaf Alhazmi')
G.add_edge('Wail Alshehri','Abdul Aziz Al-Omari*')
G.add_edge('Wail Alshehri','Waleed Alshehri')
G.add_edge('Wail Alshehri','Satam Suqami')
G.add_edge('Abdul Aziz Al-Omari*','Waleed Alshehri')
G.add_edge('Abdul Aziz Al-Omari*','Satam Suqami')
G.add_edge('Abdul Aziz Al-Omari*','Ahmed Alghamdi')
G.add_edge('Abdul Aziz Al-Omari*','Hani Hanjour')
G.add_edge('Abdul Aziz Al-Omari*','Salem Alhazmi*')
G.add_edge('Waleed Alshehri','Satam Suqami')
G.add_edge('Satam Suqami','Nabil al-Marabh')
G.add_edge('Satam Suqami','Raed Hijazi')
G.add_edge('Mohand Alshehri*','Hamza Alghamdi')
G.add_edge('Hamza Alghamdi','Ahmed Alghamdi')
G.add_edge('Hamza Alghamdi','Ahmed Al Haznawi')
G.add_edge('Hamza Alghamdi','Nawaf Alhazmi')
G.add_edge('Hamza Alghamdi','Ahmed Alnami')
G.add_edge('Hamza Alghamdi','Saeed Alghamdi*')
G.add_edge('Ahmed Alghamdi','Hani Hanjour')
G.add_edge('Ahmed Alghamdi','Salem Alhazmi*')
G.add_edge('Ahmed Alghamdi','Saeed Alghamdi*')
G.add_edge('Ahmed Al Haznawi','Nabil al-Marabh')
G.add_edge('Lofti Raissi','Hani Hanjour')
G.add_edge('Lofti Raissi','Rayed M. Abdullah')
G.add_edge('Hani Hanjour','Salem Alhazmi*')
G.add_edge('Hani Hanjour','Majed Moqed')
G.add_edge('Hani Hanjour','Khalid Al-Mihdhar')
G.add_edge('Hani Hanjour','Nawaf Alhazmi')
G.add_edge('Hani Hanjour','Bandar Alhazmi')
G.add_edge('Hani Hanjour','Rayed M. Abdullah')
G.add_edge('Hani Hanjour','Faisal Al Salmi')
G.add_edge('Salem Alhazmi*','Majed Moqed')
G.add_edge('Salem Alhazmi*','Khalid Al-Mihdhar')
G.add_edge('Salem Alhazmi*','Nawaf Alhazmi')
G.add_edge('Majed Moqed','Khalid Al-Mihdhar')
G.add_edge('Majed Moqed','Nawaf Alhazmi')
G.add_edge('Khalid Al-Mihdhar','Nawaf Alhazmi')
G.add_edge('Khalid Al-Mihdhar','Osama Awadallah')
G.add_edge('Khalid Al-Mihdhar','Abdussattar Shaikh')
G.add_edge('Nawaf Alhazmi','Osama Awadallah')
G.add_edge('Nawaf Alhazmi','Abdussattar Shaikh')
G.add_edge('Nawaf Alhazmi','Mohamed Abdi')
G.add_edge('Nawaf Alhazmi','Ahmed Alnami')
G.add_edge('Nawaf Alhazmi','Saeed Alghamdi*')
G.add_edge('Bandar Alhazmi','Rayed M. Abdullah')
G.add_edge('Rayed M. Abdullah','Faisal Al Salmi')
G.add_edge('Osama Awadallah','Abdussattar Shaikh')
G.add_edge('Ahmed Alnami','Saeed Alghamdi*')
G.add_edge('Saeed Alghamdi*','Nabil al-Marabh')
G.add_edge('Saeed Alghamdi*','Raed Hijazi')
G.add_edge('Nabil al-Marabh','Raed Hijazi')


nx.draw(G,nodecolor='r', edge_color='b', with_labels = True, font_weight='bold')
plt.show()

a =nx.degree(G)
print('degree:',a)


centrality = nx.eigenvector_centrality_numpy(G)
print('eigenvector_centrality:',centrality)


katz = nx.katz_centrality(G)
print('katz:',katz)

BC = nx.betweenness_centrality(G,normalized=False)
print('BC:',BC)


clustering = nx.clustering(G)
print('clustering:',clustering)

ekscentricitet = nx.eccentricity(G)
print(ekscentricitet)
